%% Import data from text file.
% Script for importing data from the following data file:
%
%    C:\Users\Ondra\Documents\_Development\_Projects\10_Test03\data\2013_10_22\log_LKPR_01.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/11/04 16:53:25
% Corrected by Ondrej Bruna on 2013/11/07

%% Initialize variables.
OLD = pwd;
% cd('C:\Users\Ondra\Documents\_Development\_Projects\11_Test04');
[filename filepath] = uigetfile('*.*');
filename = strcat(filepath,filename);
% filename = 'C:\Users\Ondra\Documents\_Development\_Projects\10_Test03\data\2013_10_22\log_LKRK_04.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
%   column75: double (%f)
%	column76: double (%f)
%   column77: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
flight_data = dataset(dataArray{1:end-1}, 'VarNames', {'Aileron','Aileron_trim','Elevator','Elevator_Trim','Ruder','Rudder_trim','Flaps','Slats','Speedbrake','Throttle1','Throttle2','Starter1','Starter2','Fuel_pump1','Fuel_pump2','Cutoff1','Cutoff2','Mixture1','Mixture2','Propeller_pitch1','Propeller_pitch2','Magnetos1','Magnetos2','Ignition1','Ignition2','Brake_left','Brake_right','Brake_parking','Steering','Gear_down','Gear_position','Gear_position1','Gear_position2','Gear_position3','Gear_position4','Engine_pump1','Engine_pump2','Electric_pump1','Electric_pump2','Battery_switch','External_power','APU_Generator','Engage_autopilot','Heading_select','Altitude_select','Bank_angle_select','Vertical_speed_select','Speed_select','Latitude_deg','Longitude_deg','Altitude_ft','Roll_deg','Pitch_deg','Heading_deg','Side_slip_rad','Airspeed_kt','Glideslope','Mach','Speed_down_fps','Speed_east_fps','Speed_nort_fps','uBody_fps','vBody_fps','wBody_fps','Vertical_speed_fps','nlf_acceleration','ned_down_accel_fps_sec','ned_east_accel_fps_sec','ned_north_accel_fps_sec','pilot_x_accel_fps_sec','pilot_y_accel_fps_sec','pilot_z_accel_fps_sec','elevator_pos_norm','flap_pos_norm','left_aileron_pos_norm','right_aileron_pos_norm','rudder_pos_norm','engine_running','rpm'});
%% Clear temporary variables
% clearvars filename delimiter formatSpec fileID dataArray ans;

%% Plot the trajectory
plot3(flight_data.Longitude_deg,flight_data.Latitude_deg, flight_data.Altitude_ft)

cd(OLD);